office_poll_topic/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'office_poll_topic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url('^poll/', include('poll.urls', namespace='poll') ),
    url(r'^admin/', include(admin.site.urls) ),
    url(r'^login', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout', 'django.contrib.auth.views.logout'),
)

poll/urls.py
from django.conf.urls import patterns, url

from poll import views

urlpatterns = patterns('',
    # ex: /poll/
    url(r'^$', views.index, name='index'),
    # ex poll/1/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: poll/1/results
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: poll/1/vote
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    # ex: poll/1/sendemail here is the view to send the emails for a given poll
    url(r'^(?P<poll_id>\d+)/sendemail/$', views.sendEmail, name='sendEmail'),
)

poll/models.py
from django.db import models
from django.db.models import Count


class Users(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email_address = models.CharField(max_length=50)
    is_admin = models.SmallIntegerField(null=False, default=0)
    is_active = models.SmallIntegerField(null=False, default=1)

    def __unicode__(self):
        return self.email_address
    

class Questions(models.Model):
    QUESTION_TYPE = ( ('multi-choice','multiple choice'), ('essay','free-form essay'), )
    poll_title = models.CharField(max_length=50)
    question_text = models.CharField(max_length=250)
    question_type = models.CharField(max_length=25, choices=QUESTION_TYPE)
    begin_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def get_poll_results(self, poll_id):
        return Votes.objects.filter(answer_value__question__id = poll_id).values('answer_value') \
        .annotate(vote_count=Count('answer_value'))

    def __unicode__(self):
        return self.question_text

    class Meta:
        permissions=(
            ("can_send_poll_emails","Can send poll emails"
            ),
        )


class Answers(models.Model):
    question = models.ForeignKey(Questions)
    answer_text = models.CharField(max_length=100)

    def __unicode__(self):
        return self.answer_text


class Votes(models.Model):
    answer_value = models.ForeignKey(Answers)
    voter = models.ForeignKey(Users)
    answer_timestamp = models.DateTimeField()

    def __unicode__(self):
        return str(self.answer_value)


class Users_Questions_Hash(models.Model):
    voter = models.ForeignKey(Users)
    question = models.ForeignKey(Questions)
    hash_value = models.CharField(max_length=255)
    is_valid = models.SmallIntegerField(null=False, default=1)
    
    def __unicode__(self):
        return self.voter

poll/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template import Context
from django.template.loader import render_to_string
from django.utils import timezone
from django.forms import ModelForm
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
import hashlib
import random
from poll.models import Questions, Answers, Votes, Users, Users_Questions_Hash

@permission_required('poll.can_send_poll_emails', login_url='/login')
def index(request):
    recent_question_list = Questions.objects.all().order_by('-end_date')
    context = { 'recent_question_list': recent_question_list }
    return render(request, 'poll/index.html', context) 

# the entire site will be SSL (certificate). for internal testing use a self-signed cert.
# the details page is where the URL in the email will send people. There should be code here 
# (see top sentence of comment) to validate the token and tell who is the person who clicked 
# the link. from that you also know the question. then. after they vote, i can register the results
# in the table and display the results.

def detail(request, poll_id):
    poll = get_object_or_404(Questions, pk=poll_id)
    return render(request, 'poll/detail.html', {'poll': poll } )

def results(request, poll_id):
    poll = get_object_or_404(Questions, pk=poll_id)
    allvotes2 = poll.get_poll_results(poll_id)
    allvotes = get_list_or_404(Votes.objects.filter(answer_value_id__question_id__id=poll_id ) )
    return render(request, 'poll/results.html', {'allvotes': allvotes, 'allvotes2': allvotes2, 'poll': poll} )

# in this method, use something like this: request.GET['token']
def vote(request, poll_id):
    p = get_object_or_404(Questions, pk=poll_id)
    try:
        selected_choice = p.answers_set.get(pk=request.POST['answer'])
    except (KeyError, Answers.DoesNotExist):
        # redisplay the voting form
        return render(request, 'poll/detail.html', {
            'poll': p,
            'error_message': 'Please select a choice',
        })
    # here is where to save the vote results to the Votes table
    else:
        v = Votes(answer_value=selected_choice,voter=Users.objects.get(id=3),answer_timestamp=timezone.now() )
        v.save()
        # below is the flash message.
        messages.add_message(request, messages.INFO, selected_choice)
    
    return HttpResponseRedirect(reverse('poll:results', args=(p.id,) ) )


def sendEmail(request, poll_id): 
    users = Users.objects.filter(is_active=1) 
    question = get_object_or_404(Questions, pk=poll_id)
    urlbase = request.get_host()
    for user in users:        
        salt = str(random.randint(1,10000))
        token = u'%s:%s:%s' % (user.email_address, question.question_text, salt)
        hashed_token = hashlib.sha1(token).hexdigest()
        token_link = str(urlbase) + '/vote?token=' + str(hashed_token)
        Users_Questions_Hash.objects.create(voter=user, question=question, hash_value=hashed_token, is_valid=1)
    
        subject, from_email, to = 'Vote in the latest poll!', settings.DEFAULT_FROM_EMAIL, [user.email_address]
        c = Context({'firstname': user.first_name,
            'questiontext': question.question_text,
            'tokenlink': token_link})    
        text_content = render_to_string('mail/email.txt', c)
        html_content = render_to_string('mail/email.html', c)

        msg = EmailMultiAlternatives(subject, text_content, from_email, to)
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        
    messages.add_message(request, messages.INFO, 'Emails sent successfully')

    return HttpResponseRedirect(reverse('poll:index' ) )

# http://127.0.0.1:8000/vote?token=W#$RTW#$RWSE$RAW#%$WS#$ER - this is an example of the URL

poll/templates/base.html
{% load staticfiles %}
<DOCTYPE html>
<html lang="en">

  <head>
    <title>Office Poll Topic</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static "css/test.css" %}"/>
  </head>
<body>
<h1>Office Poll Topic</h1>
  {% block content %}
  {%  endblock %}
<br>
<br>

<table fixed width="100%" colspan="3">
<td>Past Surveys</td>
<td>About</td>
<td>&copy; 2014 Pshrub</td>
</table>
</body>
</html>

poll/templates/poll/detail.html
<!-- detail.html -->
{% extends "base.html" %}
{%  block content %} 
<h2>{{ poll.question_text }}</h2>

{% if error_message  %}
    <p><strong>{{ error_message }}</strong></p>
{% endif  %}

<!-- pass along the token from the querystring, similar to the csrf_token. look into hidden inputs -->
<form action="{% url 'poll:vote' poll.id %}" method="post">
{% csrf_token  %}
{% for answer in poll.answers_set.all  %}
    <!-- <li>{{ answer.answer_text  }}</li> -->
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
{% endfor  %}
<br />
<input type="submit" value="Vote" />
</form>


{% endblock %}

poll/templates/poll/index.html
<!-- index.html -->
{% extends "base.html" %}
{%  block content %}  
<h2>Here is a list of the most current polls</h2>
{% if recent_question_list %}
    <table border="2">
    <tr>
        <th>Poll Title</th>
        <th>Poll Start Date</th>
        <th>Poll End Date</th>
        <th>Start the Poll</th>
    </tr>
    <tr>
    {% for question in recent_question_list  %}
{#      {% if question.end_date >= now %} #}
        <td><a href="{% url 'poll:detail' question.id %}">{{ question.poll_title }}</a>{{ question.start_time }}</td>
        <td>{{ question.begin_date }}</td>
        <td>{{ question.end_date }}</td>
        <td><form action="{% url 'poll:sendEmail' question.id %}"  method="post" style="margin: 0; text-align: center;">
        {% csrf_token %}<input type="submit" value="Send Email" /></form></td>
    </tr>
{#      {% else %} #}
{#        <td>&nbsp</td> #}
{#      {% endif %} #}
    {% endfor %}
</table>
{% else %}
    <p>No polls exist yet</p>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <h3{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h3>
    {% endfor %}
{% endif %}

{% endblock %}

poll/templates/poll/results.html
{# display the results here #}
<!-- results.html -->
{% extends "base.html" %}
{%  block content %} 
<h2>{{ poll.question_text }}</h2>
{% if messages %}
    {% for message in messages %}
    <h3{% if message.tags %} class="{{ message.tags }}"{% endif %}>You selected the answer: {{ message }}</h3>
    <h3>Here are the current results</h3>
    {% endfor %}
{% endif %}

<ul>
{% for answers in allvotes2 %}
    <li>{{ answers.answer_value }} : {{ answers.vote_count }}</li>
{% endfor %}
<br>
<ul>
{% for answers in allvotes %}
    <li>{{ answers.answer_value }}</li>
{% endfor %}
</ul>
<br>
<p>Thanks for your vote.</p>
<br>
<a href="{% url 'poll:index'  %}">Return to the list of poll topics</a>

{% endblock %}